#!/bin/bash
echo "You want fire?"
echo "We'll give you fire!"
for i in {10..1}
do
    echo $i
    sleep 1
done
echo "BLASTOFFFFFFF"
sleep 1
echo "                    /\\"
echo "                   //\\\\"
echo "                  ||##||"
echo "                 //##mm\\\\"
echo "                //##*mmm\\\\"
echo "               //###**mmm\\\\"
echo "              //###***nmmm\\\\"
echo "             //####***@nmmm\\\\"
echo "             ||####***@nnmm||"
echo "             ||####**@@@nnm||"
echo "             |______________|"
echo "             |    Haxle:P   |"
echo "              \____________/"
echo "               |          |"
echo "              /|    /\\    |\\"
echo "             /_|    || /\\ |_\\"
echo "               |    SpaceX|"
echo "               |       \/ |"
echo "               |          |"
echo "              /|    /\\    |\\"
echo "             / |    ||    | \\"
echo "            /  |    ||    |  \\"
echo "           /  /\\    ||    /\\  \\"
echo "          |__/  \\   ||   /  \\__|"
echo "            /____\\      /____\\"
echo "            |    |      |    |"
echo "            |    |______|    |"
echo "            |    | /--\\ |    |"
echo "            |____|/----\\|____|"
echo "             \\||/ //##\\\\ \\||/"
echo "             /##\\\//####\\\\/##\\"
echo "            //##\\\\/####\\//##\\\\"
echo "           ||/::\\||/##\\||/::\\||"
echo "           \\\\\\''///:**:\\\\\\''///"
echo "            \\\\\\///\\::::/\\\\\\///"
echo "             \\\\//\\\\\\::///\\\\//"
echo "              \/\\\\\\\\..////\\/"
echo "                 \\\\\\\\////"
echo "                  \\\\\\///"
echo "                   \\\\//"
echo "                    \\/"
